# Generated by Django 5.1.2 on 2024-10-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('curr_temp', models.IntegerField()),
                ('min_temp', models.IntegerField()),
                ('max_temp', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('wind_speed', models.IntegerField()),
                ('visibility', models.IntegerField()),
            ],
        ),
    ]
