# Generated by Django 5.1.2 on 2024-10-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_monitor_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='feels_like',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
